# Generated by Django 4.0.5 on 2022-06-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=10000)),
                ('image1_link', models.CharField(max_length=10000)),
                ('image2_link', models.CharField(max_length=10000)),
                ('image3_link', models.CharField(max_length=10000)),
                ('image4_link', models.CharField(max_length=10000)),
                ('image5_link', models.CharField(max_length=10000)),
                ('image6_link', models.CharField(max_length=10000)),
                ('sub_title', models.TextField(max_length=20000)),
            ],
        ),
    ]
