# Generated by Django 4.0.5 on 2022-06-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image1_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image2_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image3_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image4_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image5_link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image6_link',
        ),
        migrations.AddField(
            model_name='home',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='home',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='home',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='home',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='home',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='home',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
